# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.16.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
df = pd.DataFrame(X)
df

0        1       2   3   4          5  6  7  8          9
0     619   France  Female  42   2        0.0  1  1  1  101348.88
1     608    Spain  Female  41   1   83807.86  1  0  1  112542.58
2     502   France  Female  42   8   159660.8  3  1  0  113931.57
3     699   France  Female  39   1        0.0  2  0  0   93826.63
4     850    Spain  Female  43   2  125510.82  1  1  1    79084.1
...   ...      ...     ...  ..  ..        ... .. .. ..        ...
9995  771   France    Male  39   5        0.0  2  1  0   96270.64
9996  516   France    Male  35  10   57369.61  1  1  1  101699.77
9997  709   France  Female  36   7        0.0  1  0  1   42085.58
9998  772  Germany    Male  42   3   75075.31  2  1  0   92888.52
9999  792   France  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267  0.97481699
   1.36766974]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
   1.6612541 ]
 [-0.99850112 -0.57946723  1.73494238 ...  0.64920267 -1.02583358
  -0.25280688]
 ...
 [ 1.00150113 -0.57946723 -0.57638802 ... -1.54035103 -1.02583358
  -0.1427649 ]
 [ 1.00150113 -0.57946723 -0.57638802 ...  0.64920267 -1.02583358
  -0.05082558]
 [-0.99850112  1.72572313 -0.57638802 ...  0.64920267  0.97481699
  -0.81456811]]


## Part 2 - Building the ANN

### Initializing the ANN

In [14]:
model = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [15]:
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [16]:
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [17]:
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [18]:
model.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

### Training the ANN on the Training set

In [19]:
model.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100


250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 833us/step - accuracy: 0.6254 - loss: 0.6443
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 755us/step - accuracy: 0.7935 - loss: 0.4886
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 769us/step - accuracy: 0.7909 - loss: 0.4595
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 768us/step - accuracy: 0.8177 - loss: 0.4266
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 748us/step - accuracy: 0.8253 - loss: 0.4029
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 741us/step - accuracy: 0.8265 - loss: 0.4013
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 762us/step - accuracy: 0.8321 - loss: 0.3892
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - accuracy: 0.8465 - loss: 0.3690
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 740us/step - accuracy: 0.8382 - loss: 0.3773
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 746us/step - accuracy: 0.8533 - loss: 0.3615
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.8558 - loss: 0.3523
Epoch 12/100
250/250 ━━━━━━━━━━

## Save model

In [25]:
model.save('model_Churn_prediction.h5')

model_json = model.to_json()
with open("model_architecture.json", "w") as json_file:
    json_file.write(model_json)
    

# from tensorflow.keras.models import load_model

# # Memuat seluruh model
# loaded_model = load_model('model_Churn_prediction.h5')

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

In [20]:
def encode(data):
    from sklearn.compose import ColumnTransformer
    from sklearn.preprocessing import OneHotEncoder
    ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
    data = np.array(ct.fit(data))
    from sklearn.preprocessing import LabelEncoder
    le = LabelEncoder()
    data[:, 2] = le.fit(data[:, 2]) 
    return data
    
def standardize(data):
    sc.fit(data)
    return data

In [21]:
print(sc.transform([[1, 0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))

[[ 1.00150113 -0.57946723 -0.57638802 -0.53598516  0.91324755  0.10479359
  -0.69539349 -0.25781119  0.80843615  0.64920267  0.97481699 -0.87683221]]


In [22]:
print(model.predict(sc.transform([[1, 0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step
[[False]]


**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [23]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 1]
 [0 1]]


### Making the Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1537   70]
 [ 207  186]]


0.8615